<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			},
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师管理",
			            "menuJump":"列表",
			            "tableName":"jiaoshi"
			        }
			    ],
			    "menu":"教师管理"
			}
			,
           {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"成绩管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"课程管理",
                        "menuJump":"列表",
                        "tableName":"kecheng"
                    }
                ],
                "menu":"课程管理"
            },
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学科管理",
			            "menuJump":"列表",
			            "tableName":"dictionary_kemu"
			        }
			    ],
			    "menu":"学科管理"
			},
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"选课管理",
			            "menuJump":"列表",
			            "tableName":"xuanke"
			        }
			    ],
			    "menu":"选课管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"学生选课管理",
                        "menuJump":"列表",
                        "tableName":"shenqing"
                    }
                ],
                "menu":"学生选课管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	       {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                    ],
	                    "menu":"成绩管理",
	                    "menuJump":"列表",
	                    "tableName":"chengji"
	                }
	            ],
	            "menu":"成绩管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"课程管理",
	                    "menuJump":"列表",
	                    "tableName":"kecheng"
	                }
	            ],
	            "menu":"课程管理"
	        },
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			            ],
			            "menu":"学科管理",
			            "menuJump":"列表",
			            "tableName":"dictionary_kemu"
			        }
			    ],
			    "menu":"学科管理"
			},
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			            ],
			            "menu":"选课管理",
			            "menuJump":"列表",
			            "tableName":"xuanke"
			        }
			    ],
			    "menu":"选课管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "同意申请",
	                        "删除"
	                    ],
	                    "menu":"学生选课管理",
	                    "menuJump":"列表",
	                    "tableName":"shenqing"
	                }
	            ],
	            "menu":"学生选课管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	}
	,
	{
	    "backMenu":[
	       {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"成绩管理",
	                    "menuJump":"列表",
	                    "tableName":"chengji"
	                }
	            ],
	            "menu":"成绩管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"课程管理",
	                    "menuJump":"列表",
	                    "tableName":"kecheng"
	                }
	            ],
	            "menu":"课程管理"
	        },
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			            ],
			            "menu":"学科管理",
			            "menuJump":"列表",
			            "tableName":"dictionary_kemu"
			        }
			    ],
			    "menu":"学科管理"
			},
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "选课",
			            ],
			            "menu":"选课管理",
			            "menuJump":"列表",
			            "tableName":"xuanke"
			        }
			    ],
			    "menu":"选课管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "退课",
	                    ],
	                    "menu":"学生选课管理",
	                    "menuJump":"列表",
	                    "tableName":"shenqing"
	                }
	            ],
	            "menu":"学生选课管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"学生",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
